name: What2Wear CI/CD Pipeline

on:
  push:
    branches:
      - main
      - frontend-updated
  pull_request:
    branches:
      - main
      - frontend-updated

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (or appropriate JDK version for your backend)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies (if you're using Maven for backend)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and Test Backend with Debug Logging
      - name: Build and Test Backend
        run: |
          cd backend
          mvn clean install test -e -X

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use Node.js version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Cache npm dependencies
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # Step 5: Polyfill ReadableStream (for compatibility)
      - name: Polyfill ReadableStream
        run: |
          npm install readable-stream

      # Step 6: Start Expo in Web Mode with npx
      - name: Start Expo in Web Mode
        run: |
          cd frontend
          npx expo start --web

      # Step 7: Run Expo Tests (if defined)
      - name: Run Expo Tests
        run: |
          cd frontend
          npm test
