name: What2Wear CI/CD Pipeline

on:
  push:
    branches:
      - main  # This can be changed to the branch you're using for deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Use the version your backend requires

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Add Firebase service account key
      - name: Add Firebase Service Account Key
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json

      # Step 5: Build the backend
      - name: Build Backend
        run: npm run build  # Replace with your actual build command

      # Step 6: Run tests (optional)
      - name: Run Tests
        run: npm test  # If you have tests, this will execute them
