name: What2Wear CI/CD Pipeline

on:
  push:
    branches:
      - main
      - frontend-updated
  pull_request:
    branches:
      - main
      - frontend-updated

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      # Backend build steps...

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (use Node.js version 18)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Polyfill ReadableStream
        run: |
          npm install readable-stream

      - name: Start Expo in Web Mode with npx
        run: |
          cd frontend
          npx expo start --web

      - name: Run Expo Tests
        run: |
          cd frontend
          npm test
