name: What2Wear CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Test Node.js 20 Compatibility
      - name: Test Node.js 20 Compatibility
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 5: Build and Test Backend with Debug Logging
      - name: Build and Test Backend
        run: |
          cd backend
          mvn clean install test -e -X

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Cache npm packages
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install Expo CLI
      - name: Install Expo CLI
        run: npm install -g expo-cli

      # Step 5: Install Expo Dependencies
      - name: Install Expo Dependencies
        run: |
          cd frontend
          npx expo install

      # Step 6: Start Expo in Web Mode
      - name: Start Expo in Web Mode
        run: |
          cd frontend
          npx expo start --web

      # Optional Step 7: Run frontend tests if defined
      - name: Run Expo Tests
        run: |
          cd frontend
          npm test
