build_frontend:
  runs-on: ubuntu-latest

  steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js 18
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Verify Node.js version
    - name: Verify Node.js version
      run: node --version

    # Step 4: Remove npm lock file if it exists
    - name: Remove npm lock file
      run: |
        cd frontend
        rm -f package-lock.json

    # Step 5: Cache Yarn dependencies
    - name: Cache Yarn packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # Step 6: Install dependencies with Yarn
    - name: Install Expo Dependencies
      run: |
        cd frontend
        yarn install

    # Step 7: Install Expo CLI globally
    - name: Install Expo CLI
      run: yarn global add expo-cli

    # Step 8: Start Expo in Web Mode
    - name: Start Expo in Web Mode
      run: |
        cd frontend
        expo start --web
