name: Build and Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step to set Firebase credentials from the GitHub secret
      - name: Set up Firebase credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $GITHUB_ENV

      # Cache Gradle dependencies
      - name: Set up Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Install dependencies and run tests
      - name: Install dependencies
        run: |
          cd backend
          ./mvnw install

      - name: Run tests
        run: |
          cd backend
          ./mvnw test

      # Build and run the Spring Boot application
      - name: Build and run the Spring Boot application
        run: |
          cd backend
          ./mvnw spring-boot:run
