name: What2Wear CI/CD Pipeline

on:
  push:
    branches:
      - main
      - meghana
  pull_request:
    branches:
      - main
      - meghana

jobs:
  build:
    runs-on: ubuntu-22.04  # Explicitly set the Ubuntu version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to set up JDK 11 with distribution specified
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Specify the distribution (adoptopenjdk, zulu, amazon-corretto, etc.)

      # Step to set Firebase credentials from the GitHub secret
      - name: Set up Firebase credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $GITHUB_ENV

      # Cache Gradle dependencies
      - name: Set up Gradle Cache
        uses: actions/cache@v3  # Update to the latest version
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Install dependencies and run tests
      - name: Install dependencies
        run: |
          cd backend
          ./mvnw install

      - name: Run tests
        run: |
          cd backend
          ./mvnw test

      # Build and run the Spring Boot application
      - name: Build and run the Spring Boot application
        run: |
          cd backend
          ./mvnw spring-boot:run
