name: What2Wear CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and Test Backend with Debug Logging
      - name: Build and Test Backend
        run: |
          cd backend
          mvn clean install test -e -X

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Verify Node.js version
      - name: Verify Node.js version
        run: node --version

      # Step 4: Remove npm lock file
      - name: Remove npm lock file
        run: |
          cd frontend
          rm -f package-lock.json

      # Step 5: Cache Yarn dependencies
      - name: Cache Yarn packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Step 6: Install Expo Dependencies
      - name: Install Expo Dependencies
        run: |
          cd frontend
          yarn install

      # Step 7: Install Expo CLI
      - name: Install Expo CLI
        run: yarn global add expo-cli

      # Step 8: Start Expo in Web Mode
      - name: Start Expo in Web Mode
        run: |
          cd frontend
          expo start --web
